/* automatically generated by rust-bindgen */

#![allow(dead_code,
         non_camel_case_types,
         non_upper_case_globals,
         non_snake_case)]
pub type size_t = usize;
pub type __u_char = ::libc::c_uchar;
pub type __u_short = ::libc::c_ushort;
pub type __u_int = ::libc::c_uint;
pub type __u_long = ::libc::c_ulong;
pub type __int8_t = ::libc::c_char;
pub type __uint8_t = ::libc::c_uchar;
pub type __int16_t = ::libc::c_short;
pub type __uint16_t = ::libc::c_ushort;
pub type __int32_t = ::libc::c_int;
pub type __uint32_t = ::libc::c_uint;
pub type __int64_t = ::libc::c_long;
pub type __uint64_t = ::libc::c_ulong;
pub type __quad_t = ::libc::c_long;
pub type __u_quad_t = ::libc::c_ulong;
pub type __dev_t = ::libc::c_ulong;
pub type __uid_t = ::libc::c_uint;
pub type __gid_t = ::libc::c_uint;
pub type __ino_t = ::libc::c_ulong;
pub type __ino64_t = ::libc::c_ulong;
pub type __mode_t = ::libc::c_uint;
pub type __nlink_t = ::libc::c_ulong;
pub type __off_t = ::libc::c_long;
pub type __off64_t = ::libc::c_long;
pub type __pid_t = ::libc::c_int;
#[repr(C)]
#[derive(Copy, Clone)]
#[derive(Debug)]
pub struct __fsid_t {
    pub __val: [::libc::c_int; 2usize],
}
impl ::core::default::Default for __fsid_t {
    fn default() -> Self { unsafe { ::core::mem::zeroed() } }
}
pub type __clock_t = ::libc::c_long;
pub type __rlim_t = ::libc::c_ulong;
pub type __rlim64_t = ::libc::c_ulong;
pub type __id_t = ::libc::c_uint;
pub type __time_t = ::libc::c_long;
pub type __useconds_t = ::libc::c_uint;
pub type __suseconds_t = ::libc::c_long;
pub type __daddr_t = ::libc::c_int;
pub type __key_t = ::libc::c_int;
pub type __clockid_t = ::libc::c_int;
pub type __timer_t = *mut ::libc::c_void;
pub type __blksize_t = ::libc::c_long;
pub type __blkcnt_t = ::libc::c_long;
pub type __blkcnt64_t = ::libc::c_long;
pub type __fsblkcnt_t = ::libc::c_ulong;
pub type __fsblkcnt64_t = ::libc::c_ulong;
pub type __fsfilcnt_t = ::libc::c_ulong;
pub type __fsfilcnt64_t = ::libc::c_ulong;
pub type __fsword_t = ::libc::c_long;
pub type __ssize_t = ::libc::c_long;
pub type __syscall_slong_t = ::libc::c_long;
pub type __syscall_ulong_t = ::libc::c_ulong;
pub type __loff_t = __off64_t;
pub type __qaddr_t = *mut __quad_t;
pub type __caddr_t = *mut ::libc::c_char;
pub type __intptr_t = ::libc::c_long;
pub type __socklen_t = ::libc::c_uint;
pub type FILE = _IO_FILE;
pub type __FILE = _IO_FILE;
#[repr(C)]
#[derive(Copy, Clone)]
#[derive(Debug)]
pub struct __mbstate_t {
    pub __count: ::libc::c_int,
    pub __value: Union_Unnamed1,
}
impl ::core::default::Default for __mbstate_t {
    fn default() -> Self { unsafe { ::core::mem::zeroed() } }
}
#[repr(C)]
#[derive(Copy, Clone)]
#[derive(Debug)]
pub struct Union_Unnamed1 {
    pub _bindgen_data_: [u32; 1usize],
}
impl Union_Unnamed1 {
    pub unsafe fn __wch(&mut self) -> *mut ::libc::c_uint {
        let raw: *mut u8 = ::core::mem::transmute(&self._bindgen_data_);
        ::core::mem::transmute(raw.offset(0))
    }
    pub unsafe fn __wchb(&mut self) -> *mut [::libc::c_char; 4usize] {
        let raw: *mut u8 = ::core::mem::transmute(&self._bindgen_data_);
        ::core::mem::transmute(raw.offset(0))
    }
}
impl ::core::default::Default for Union_Unnamed1 {
    fn default() -> Self { unsafe { ::core::mem::zeroed() } }
}
#[repr(C)]
#[derive(Copy, Clone)]
#[derive(Debug)]
pub struct _G_fpos_t {
    pub __pos: __off_t,
    pub __state: __mbstate_t,
}
impl ::core::default::Default for _G_fpos_t {
    fn default() -> Self { unsafe { ::core::mem::zeroed() } }
}
#[repr(C)]
#[derive(Copy, Clone)]
#[derive(Debug)]
pub struct _G_fpos64_t {
    pub __pos: __off64_t,
    pub __state: __mbstate_t,
}
impl ::core::default::Default for _G_fpos64_t {
    fn default() -> Self { unsafe { ::core::mem::zeroed() } }
}
pub type va_list = __gnuc_va_list;
pub type __gnuc_va_list = __builtin_va_list;
pub enum _IO_jump_t { }
pub type _IO_lock_t = ::libc::c_void;
#[repr(C)]
#[derive(Copy, Clone)]
#[derive(Debug)]
pub struct _IO_marker {
    pub _next: *mut _IO_marker,
    pub _sbuf: *mut _IO_FILE,
    pub _pos: ::libc::c_int,
    _bindgen_padding_0_: [u8; 4usize],
}
impl ::core::default::Default for _IO_marker {
    fn default() -> Self { unsafe { ::core::mem::zeroed() } }
}
#[derive(Copy, Clone)]
#[repr(u32)]
#[derive(Debug)]
pub enum __codecvt_result {
    __codecvt_ok = 0,
    __codecvt_partial = 1,
    __codecvt_error = 2,
    __codecvt_noconv = 3,
}
#[repr(C)]
#[derive(Copy, Clone)]
#[derive(Debug)]
pub struct _IO_FILE {
    pub _flags: ::libc::c_int,
    pub _IO_read_ptr: *mut ::libc::c_char,
    pub _IO_read_end: *mut ::libc::c_char,
    pub _IO_read_base: *mut ::libc::c_char,
    pub _IO_write_base: *mut ::libc::c_char,
    pub _IO_write_ptr: *mut ::libc::c_char,
    pub _IO_write_end: *mut ::libc::c_char,
    pub _IO_buf_base: *mut ::libc::c_char,
    pub _IO_buf_end: *mut ::libc::c_char,
    pub _IO_save_base: *mut ::libc::c_char,
    pub _IO_backup_base: *mut ::libc::c_char,
    pub _IO_save_end: *mut ::libc::c_char,
    pub _markers: *mut _IO_marker,
    pub _chain: *mut _IO_FILE,
    pub _fileno: ::libc::c_int,
    pub _flags2: ::libc::c_int,
    pub _old_offset: __off_t,
    pub _cur_column: ::libc::c_ushort,
    pub _vtable_offset: ::libc::c_char,
    pub _shortbuf: [::libc::c_char; 1usize],
    pub _lock: *mut _IO_lock_t,
    pub _offset: __off64_t,
    pub __pad1: *mut ::libc::c_void,
    pub __pad2: *mut ::libc::c_void,
    pub __pad3: *mut ::libc::c_void,
    pub __pad4: *mut ::libc::c_void,
    pub __pad5: size_t,
    pub _mode: ::libc::c_int,
    pub _unused2: [::libc::c_char; 20usize],
}
impl ::core::default::Default for _IO_FILE {
    fn default() -> Self { unsafe { ::core::mem::zeroed() } }
}
pub enum _IO_FILE_plus { }
pub type __io_read_fn =
    ::core::option::Option<unsafe extern "C" fn(__cookie: *mut ::libc::c_void,
                                                __buf: *mut ::libc::c_char,
                                                __nbytes: size_t)
                               -> __ssize_t>;
pub type __io_write_fn =
    ::core::option::Option<unsafe extern "C" fn(__cookie: *mut ::libc::c_void,
                                                __buf: *const ::libc::c_char,
                                                __n: size_t) -> __ssize_t>;
pub type __io_seek_fn =
    ::core::option::Option<unsafe extern "C" fn(__cookie: *mut ::libc::c_void,
                                                __pos: *mut __off64_t,
                                                __w: ::libc::c_int)
                               -> ::libc::c_int>;
pub type __io_close_fn =
    ::core::option::Option<unsafe extern "C" fn(__cookie: *mut ::libc::c_void)
                               -> ::libc::c_int>;
pub type off_t = __off_t;
pub type ssize_t = isize;
pub type fpos_t = _G_fpos_t;
pub type int8_t = i8;
pub type int16_t = i16;
pub type int32_t = i32;
pub type int64_t = i64;
pub type uint8_t = u8;
pub type uint16_t = u16;
pub type uint32_t = u32;
pub type uint64_t = u64;
pub type int_least8_t = ::libc::c_char;
pub type int_least16_t = ::libc::c_short;
pub type int_least32_t = ::libc::c_int;
pub type int_least64_t = ::libc::c_long;
pub type uint_least8_t = ::libc::c_uchar;
pub type uint_least16_t = ::libc::c_ushort;
pub type uint_least32_t = ::libc::c_uint;
pub type uint_least64_t = ::libc::c_ulong;
pub type int_fast8_t = ::libc::c_char;
pub type int_fast16_t = ::libc::c_long;
pub type int_fast32_t = ::libc::c_long;
pub type int_fast64_t = ::libc::c_long;
pub type uint_fast8_t = ::libc::c_uchar;
pub type uint_fast16_t = ::libc::c_ulong;
pub type uint_fast32_t = ::libc::c_ulong;
pub type uint_fast64_t = ::libc::c_ulong;
pub type intptr_t = isize;
pub type uintptr_t = usize;
pub type intmax_t = ::libc::c_long;
pub type uintmax_t = ::libc::c_ulong;
pub type __gwchar_t = ::libc::c_int;
#[repr(C)]
#[derive(Copy, Clone)]
#[derive(Debug)]
pub struct imaxdiv_t {
    pub quot: ::libc::c_long,
    pub rem: ::libc::c_long,
}
impl ::core::default::Default for imaxdiv_t {
    fn default() -> Self { unsafe { ::core::mem::zeroed() } }
}
pub type u_char = __u_char;
pub type u_short = __u_short;
pub type u_int = __u_int;
pub type u_long = __u_long;
pub type quad_t = __quad_t;
pub type u_quad_t = __u_quad_t;
pub type fsid_t = __fsid_t;
pub type loff_t = __loff_t;
pub type ino_t = __ino_t;
pub type dev_t = __dev_t;
pub type gid_t = __gid_t;
pub type mode_t = __mode_t;
pub type nlink_t = __nlink_t;
pub type uid_t = __uid_t;
pub type pid_t = __pid_t;
pub type id_t = __id_t;
pub type daddr_t = __daddr_t;
pub type caddr_t = __caddr_t;
pub type key_t = __key_t;
pub type clock_t = __clock_t;
pub type time_t = __time_t;
pub type clockid_t = __clockid_t;
pub type timer_t = __timer_t;
pub type ulong = ::libc::c_ulong;
pub type ushort = ::libc::c_ushort;
pub type uint_ = ::libc::c_uint;
pub type u_int8_t = ::libc::c_uchar;
pub type u_int16_t = ::libc::c_ushort;
pub type u_int32_t = ::libc::c_uint;
pub type u_int64_t = ::libc::c_ulong;
pub type register_t = ::libc::c_long;
pub type __sig_atomic_t = ::libc::c_int;
#[repr(C)]
#[derive(Copy, Clone)]
#[derive(Debug)]
pub struct __sigset_t {
    pub __val: [::libc::c_ulong; 16usize],
}
impl ::core::default::Default for __sigset_t {
    fn default() -> Self { unsafe { ::core::mem::zeroed() } }
}
pub type sigset_t = __sigset_t;
#[repr(C)]
#[derive(Copy, Clone)]
#[derive(Debug)]
pub struct timespec {
    pub tv_sec: __time_t,
    pub tv_nsec: __syscall_slong_t,
}
impl ::core::default::Default for timespec {
    fn default() -> Self { unsafe { ::core::mem::zeroed() } }
}
#[repr(C)]
#[derive(Copy, Clone)]
#[derive(Debug)]
pub struct timeval {
    pub tv_sec: __time_t,
    pub tv_usec: __suseconds_t,
}
impl ::core::default::Default for timeval {
    fn default() -> Self { unsafe { ::core::mem::zeroed() } }
}
pub type suseconds_t = __suseconds_t;
pub type __fd_mask = ::libc::c_long;
#[repr(C)]
#[derive(Copy, Clone)]
#[derive(Debug)]
pub struct fd_set {
    pub __fds_bits: [__fd_mask; 16usize],
}
impl ::core::default::Default for fd_set {
    fn default() -> Self { unsafe { ::core::mem::zeroed() } }
}
pub type fd_mask = __fd_mask;
pub type blksize_t = __blksize_t;
pub type blkcnt_t = __blkcnt_t;
pub type fsblkcnt_t = __fsblkcnt_t;
pub type fsfilcnt_t = __fsfilcnt_t;
pub type pthread_t = ::libc::c_ulong;
#[repr(C)]
#[derive(Copy)]
pub struct pthread_attr_t {
    pub _bindgen_data_: [u64; 7usize],
}
impl pthread_attr_t {
    pub unsafe fn __size(&mut self) -> *mut [::libc::c_char; 56usize] {
        let raw: *mut u8 = ::core::mem::transmute(&self._bindgen_data_);
        ::core::mem::transmute(raw.offset(0))
    }
    pub unsafe fn __align(&mut self) -> *mut ::libc::c_long {
        let raw: *mut u8 = ::core::mem::transmute(&self._bindgen_data_);
        ::core::mem::transmute(raw.offset(0))
    }
}
impl ::core::clone::Clone for pthread_attr_t {
    fn clone(&self) -> Self { *self }
}
impl ::core::default::Default for pthread_attr_t {
    fn default() -> Self { unsafe { ::core::mem::zeroed() } }
}
#[repr(C)]
#[derive(Copy, Clone)]
#[derive(Debug)]
pub struct __pthread_internal_list {
    pub __prev: *mut __pthread_internal_list,
    pub __next: *mut __pthread_internal_list,
}
impl ::core::default::Default for __pthread_internal_list {
    fn default() -> Self { unsafe { ::core::mem::zeroed() } }
}
pub type __pthread_list_t = __pthread_internal_list;
#[repr(C)]
#[derive(Copy)]
pub struct pthread_mutex_t {
    pub _bindgen_data_: [u64; 5usize],
}
impl pthread_mutex_t {
    pub unsafe fn __data(&mut self) -> *mut __pthread_mutex_s {
        let raw: *mut u8 = ::core::mem::transmute(&self._bindgen_data_);
        ::core::mem::transmute(raw.offset(0))
    }
    pub unsafe fn __size(&mut self) -> *mut [::libc::c_char; 40usize] {
        let raw: *mut u8 = ::core::mem::transmute(&self._bindgen_data_);
        ::core::mem::transmute(raw.offset(0))
    }
    pub unsafe fn __align(&mut self) -> *mut ::libc::c_long {
        let raw: *mut u8 = ::core::mem::transmute(&self._bindgen_data_);
        ::core::mem::transmute(raw.offset(0))
    }
}
impl ::core::clone::Clone for pthread_mutex_t {
    fn clone(&self) -> Self { *self }
}
impl ::core::default::Default for pthread_mutex_t {
    fn default() -> Self { unsafe { ::core::mem::zeroed() } }
}
#[repr(C)]
#[derive(Copy, Clone)]
#[derive(Debug)]
pub struct __pthread_mutex_s {
    pub __lock: ::libc::c_int,
    pub __count: ::libc::c_uint,
    pub __owner: ::libc::c_int,
    pub __nusers: ::libc::c_uint,
    pub __kind: ::libc::c_int,
    pub __spins: ::libc::c_short,
    pub __elision: ::libc::c_short,
    pub __list: __pthread_list_t,
}
impl ::core::default::Default for __pthread_mutex_s {
    fn default() -> Self { unsafe { ::core::mem::zeroed() } }
}
#[repr(C)]
#[derive(Copy, Clone)]
#[derive(Debug)]
pub struct pthread_mutexattr_t {
    pub _bindgen_data_: [u32; 1usize],
}
impl pthread_mutexattr_t {
    pub unsafe fn __size(&mut self) -> *mut [::libc::c_char; 4usize] {
        let raw: *mut u8 = ::core::mem::transmute(&self._bindgen_data_);
        ::core::mem::transmute(raw.offset(0))
    }
    pub unsafe fn __align(&mut self) -> *mut ::libc::c_int {
        let raw: *mut u8 = ::core::mem::transmute(&self._bindgen_data_);
        ::core::mem::transmute(raw.offset(0))
    }
}
impl ::core::default::Default for pthread_mutexattr_t {
    fn default() -> Self { unsafe { ::core::mem::zeroed() } }
}
#[repr(C)]
#[derive(Copy)]
pub struct pthread_cond_t {
    pub _bindgen_data_: [u64; 6usize],
}
impl pthread_cond_t {
    pub unsafe fn __data(&mut self) -> *mut Struct_Unnamed2 {
        let raw: *mut u8 = ::core::mem::transmute(&self._bindgen_data_);
        ::core::mem::transmute(raw.offset(0))
    }
    pub unsafe fn __size(&mut self) -> *mut [::libc::c_char; 48usize] {
        let raw: *mut u8 = ::core::mem::transmute(&self._bindgen_data_);
        ::core::mem::transmute(raw.offset(0))
    }
    pub unsafe fn __align(&mut self) -> *mut ::libc::c_longlong {
        let raw: *mut u8 = ::core::mem::transmute(&self._bindgen_data_);
        ::core::mem::transmute(raw.offset(0))
    }
}
impl ::core::clone::Clone for pthread_cond_t {
    fn clone(&self) -> Self { *self }
}
impl ::core::default::Default for pthread_cond_t {
    fn default() -> Self { unsafe { ::core::mem::zeroed() } }
}
#[repr(C)]
#[derive(Copy, Clone)]
#[derive(Debug)]
pub struct Struct_Unnamed2 {
    pub __lock: ::libc::c_int,
    pub __futex: ::libc::c_uint,
    pub __total_seq: ::libc::c_ulonglong,
    pub __wakeup_seq: ::libc::c_ulonglong,
    pub __woken_seq: ::libc::c_ulonglong,
    pub __mutex: *mut ::libc::c_void,
    pub __nwaiters: ::libc::c_uint,
    pub __broadcast_seq: ::libc::c_uint,
}
impl ::core::default::Default for Struct_Unnamed2 {
    fn default() -> Self { unsafe { ::core::mem::zeroed() } }
}
#[repr(C)]
#[derive(Copy, Clone)]
#[derive(Debug)]
pub struct pthread_condattr_t {
    pub _bindgen_data_: [u32; 1usize],
}
impl pthread_condattr_t {
    pub unsafe fn __size(&mut self) -> *mut [::libc::c_char; 4usize] {
        let raw: *mut u8 = ::core::mem::transmute(&self._bindgen_data_);
        ::core::mem::transmute(raw.offset(0))
    }
    pub unsafe fn __align(&mut self) -> *mut ::libc::c_int {
        let raw: *mut u8 = ::core::mem::transmute(&self._bindgen_data_);
        ::core::mem::transmute(raw.offset(0))
    }
}
impl ::core::default::Default for pthread_condattr_t {
    fn default() -> Self { unsafe { ::core::mem::zeroed() } }
}
pub type pthread_key_t = ::libc::c_uint;
pub type pthread_once_t = ::libc::c_int;
#[repr(C)]
#[derive(Copy)]
pub struct pthread_rwlock_t {
    pub _bindgen_data_: [u64; 7usize],
}
impl pthread_rwlock_t {
    pub unsafe fn __data(&mut self) -> *mut Struct_Unnamed3 {
        let raw: *mut u8 = ::core::mem::transmute(&self._bindgen_data_);
        ::core::mem::transmute(raw.offset(0))
    }
    pub unsafe fn __size(&mut self) -> *mut [::libc::c_char; 56usize] {
        let raw: *mut u8 = ::core::mem::transmute(&self._bindgen_data_);
        ::core::mem::transmute(raw.offset(0))
    }
    pub unsafe fn __align(&mut self) -> *mut ::libc::c_long {
        let raw: *mut u8 = ::core::mem::transmute(&self._bindgen_data_);
        ::core::mem::transmute(raw.offset(0))
    }
}
impl ::core::clone::Clone for pthread_rwlock_t {
    fn clone(&self) -> Self { *self }
}
impl ::core::default::Default for pthread_rwlock_t {
    fn default() -> Self { unsafe { ::core::mem::zeroed() } }
}
#[repr(C)]
#[derive(Copy, Clone)]
#[derive(Debug)]
pub struct Struct_Unnamed3 {
    pub __lock: ::libc::c_int,
    pub __nr_readers: ::libc::c_uint,
    pub __readers_wakeup: ::libc::c_uint,
    pub __writer_wakeup: ::libc::c_uint,
    pub __nr_readers_queued: ::libc::c_uint,
    pub __nr_writers_queued: ::libc::c_uint,
    pub __writer: ::libc::c_int,
    pub __shared: ::libc::c_int,
    pub __rwelision: ::libc::c_char,
    pub __pad1: [::libc::c_uchar; 7usize],
    pub __pad2: ::libc::c_ulong,
    pub __flags: ::libc::c_uint,
}
impl ::core::default::Default for Struct_Unnamed3 {
    fn default() -> Self { unsafe { ::core::mem::zeroed() } }
}
#[repr(C)]
#[derive(Copy, Clone)]
#[derive(Debug)]
pub struct pthread_rwlockattr_t {
    pub _bindgen_data_: [u64; 1usize],
}
impl pthread_rwlockattr_t {
    pub unsafe fn __size(&mut self) -> *mut [::libc::c_char; 8usize] {
        let raw: *mut u8 = ::core::mem::transmute(&self._bindgen_data_);
        ::core::mem::transmute(raw.offset(0))
    }
    pub unsafe fn __align(&mut self) -> *mut ::libc::c_long {
        let raw: *mut u8 = ::core::mem::transmute(&self._bindgen_data_);
        ::core::mem::transmute(raw.offset(0))
    }
}
impl ::core::default::Default for pthread_rwlockattr_t {
    fn default() -> Self { unsafe { ::core::mem::zeroed() } }
}
pub type pthread_spinlock_t = ::libc::c_int;
#[repr(C)]
#[derive(Copy, Clone)]
#[derive(Debug)]
pub struct pthread_barrier_t {
    pub _bindgen_data_: [u64; 4usize],
}
impl pthread_barrier_t {
    pub unsafe fn __size(&mut self) -> *mut [::libc::c_char; 32usize] {
        let raw: *mut u8 = ::core::mem::transmute(&self._bindgen_data_);
        ::core::mem::transmute(raw.offset(0))
    }
    pub unsafe fn __align(&mut self) -> *mut ::libc::c_long {
        let raw: *mut u8 = ::core::mem::transmute(&self._bindgen_data_);
        ::core::mem::transmute(raw.offset(0))
    }
}
impl ::core::default::Default for pthread_barrier_t {
    fn default() -> Self { unsafe { ::core::mem::zeroed() } }
}
#[repr(C)]
#[derive(Copy, Clone)]
#[derive(Debug)]
pub struct pthread_barrierattr_t {
    pub _bindgen_data_: [u32; 1usize],
}
impl pthread_barrierattr_t {
    pub unsafe fn __size(&mut self) -> *mut [::libc::c_char; 4usize] {
        let raw: *mut u8 = ::core::mem::transmute(&self._bindgen_data_);
        ::core::mem::transmute(raw.offset(0))
    }
    pub unsafe fn __align(&mut self) -> *mut ::libc::c_int {
        let raw: *mut u8 = ::core::mem::transmute(&self._bindgen_data_);
        ::core::mem::transmute(raw.offset(0))
    }
}
impl ::core::default::Default for pthread_barrierattr_t {
    fn default() -> Self { unsafe { ::core::mem::zeroed() } }
}
#[derive(Copy, Clone)]
#[repr(u32)]
#[derive(Debug)]
pub enum rd_kafka_type_t { RD_KAFKA_PRODUCER = 0, RD_KAFKA_CONSUMER = 1, }
#[derive(Copy, Clone)]
#[repr(u32)]
#[derive(Debug)]
pub enum rd_kafka_timestamp_type_t {
    RD_KAFKA_TIMESTAMP_NOT_AVAILABLE = 0,
    RD_KAFKA_TIMESTAMP_CREATE_TIME = 1,
    RD_KAFKA_TIMESTAMP_LOG_APPEND_TIME = 2,
}
pub enum rd_kafka_s { }
pub type rd_kafka_t = rd_kafka_s;
pub enum rd_kafka_topic_s { }
pub type rd_kafka_topic_t = rd_kafka_topic_s;
pub enum rd_kafka_conf_s { }
pub type rd_kafka_conf_t = rd_kafka_conf_s;
pub enum rd_kafka_topic_conf_s { }
pub type rd_kafka_topic_conf_t = rd_kafka_topic_conf_s;
pub enum rd_kafka_queue_s { }
pub type rd_kafka_queue_t = rd_kafka_queue_s;
#[derive(Copy, Clone)]
#[repr(i32)]
#[derive(Debug)]
pub enum rd_kafka_resp_err_t {
    RD_KAFKA_RESP_ERR__BEGIN = -200,
    RD_KAFKA_RESP_ERR__BAD_MSG = -199,
    RD_KAFKA_RESP_ERR__BAD_COMPRESSION = -198,
    RD_KAFKA_RESP_ERR__DESTROY = -197,
    RD_KAFKA_RESP_ERR__FAIL = -196,
    RD_KAFKA_RESP_ERR__TRANSPORT = -195,
    RD_KAFKA_RESP_ERR__CRIT_SYS_RESOURCE = -194,
    RD_KAFKA_RESP_ERR__RESOLVE = -193,
    RD_KAFKA_RESP_ERR__MSG_TIMED_OUT = -192,
    RD_KAFKA_RESP_ERR__PARTITION_EOF = -191,
    RD_KAFKA_RESP_ERR__UNKNOWN_PARTITION = -190,
    RD_KAFKA_RESP_ERR__FS = -189,
    RD_KAFKA_RESP_ERR__UNKNOWN_TOPIC = -188,
    RD_KAFKA_RESP_ERR__ALL_BROKERS_DOWN = -187,
    RD_KAFKA_RESP_ERR__INVALID_ARG = -186,
    RD_KAFKA_RESP_ERR__TIMED_OUT = -185,
    RD_KAFKA_RESP_ERR__QUEUE_FULL = -184,
    RD_KAFKA_RESP_ERR__ISR_INSUFF = -183,
    RD_KAFKA_RESP_ERR__NODE_UPDATE = -182,
    RD_KAFKA_RESP_ERR__SSL = -181,
    RD_KAFKA_RESP_ERR__WAIT_COORD = -180,
    RD_KAFKA_RESP_ERR__UNKNOWN_GROUP = -179,
    RD_KAFKA_RESP_ERR__IN_PROGRESS = -178,
    RD_KAFKA_RESP_ERR__PREV_IN_PROGRESS = -177,
    RD_KAFKA_RESP_ERR__EXISTING_SUBSCRIPTION = -176,
    RD_KAFKA_RESP_ERR__ASSIGN_PARTITIONS = -175,
    RD_KAFKA_RESP_ERR__REVOKE_PARTITIONS = -174,
    RD_KAFKA_RESP_ERR__CONFLICT = -173,
    RD_KAFKA_RESP_ERR__STATE = -172,
    RD_KAFKA_RESP_ERR__UNKNOWN_PROTOCOL = -171,
    RD_KAFKA_RESP_ERR__NOT_IMPLEMENTED = -170,
    RD_KAFKA_RESP_ERR__AUTHENTICATION = -169,
    RD_KAFKA_RESP_ERR__NO_OFFSET = -168,
    RD_KAFKA_RESP_ERR__OUTDATED = -167,
    RD_KAFKA_RESP_ERR__END = -100,
    RD_KAFKA_RESP_ERR_UNKNOWN = -1,
    RD_KAFKA_RESP_ERR_NO_ERROR = 0,
    RD_KAFKA_RESP_ERR_OFFSET_OUT_OF_RANGE = 1,
    RD_KAFKA_RESP_ERR_INVALID_MSG = 2,
    RD_KAFKA_RESP_ERR_UNKNOWN_TOPIC_OR_PART = 3,
    RD_KAFKA_RESP_ERR_INVALID_MSG_SIZE = 4,
    RD_KAFKA_RESP_ERR_LEADER_NOT_AVAILABLE = 5,
    RD_KAFKA_RESP_ERR_NOT_LEADER_FOR_PARTITION = 6,
    RD_KAFKA_RESP_ERR_REQUEST_TIMED_OUT = 7,
    RD_KAFKA_RESP_ERR_BROKER_NOT_AVAILABLE = 8,
    RD_KAFKA_RESP_ERR_REPLICA_NOT_AVAILABLE = 9,
    RD_KAFKA_RESP_ERR_MSG_SIZE_TOO_LARGE = 10,
    RD_KAFKA_RESP_ERR_STALE_CTRL_EPOCH = 11,
    RD_KAFKA_RESP_ERR_OFFSET_METADATA_TOO_LARGE = 12,
    RD_KAFKA_RESP_ERR_NETWORK_EXCEPTION = 13,
    RD_KAFKA_RESP_ERR_GROUP_LOAD_IN_PROGRESS = 14,
    RD_KAFKA_RESP_ERR_GROUP_COORDINATOR_NOT_AVAILABLE = 15,
    RD_KAFKA_RESP_ERR_NOT_COORDINATOR_FOR_GROUP = 16,
    RD_KAFKA_RESP_ERR_TOPIC_EXCEPTION = 17,
    RD_KAFKA_RESP_ERR_RECORD_LIST_TOO_LARGE = 18,
    RD_KAFKA_RESP_ERR_NOT_ENOUGH_REPLICAS = 19,
    RD_KAFKA_RESP_ERR_NOT_ENOUGH_REPLICAS_AFTER_APPEND = 20,
    RD_KAFKA_RESP_ERR_INVALID_REQUIRED_ACKS = 21,
    RD_KAFKA_RESP_ERR_ILLEGAL_GENERATION = 22,
    RD_KAFKA_RESP_ERR_INCONSISTENT_GROUP_PROTOCOL = 23,
    RD_KAFKA_RESP_ERR_INVALID_GROUP_ID = 24,
    RD_KAFKA_RESP_ERR_UNKNOWN_MEMBER_ID = 25,
    RD_KAFKA_RESP_ERR_INVALID_SESSION_TIMEOUT = 26,
    RD_KAFKA_RESP_ERR_REBALANCE_IN_PROGRESS = 27,
    RD_KAFKA_RESP_ERR_INVALID_COMMIT_OFFSET_SIZE = 28,
    RD_KAFKA_RESP_ERR_TOPIC_AUTHORIZATION_FAILED = 29,
    RD_KAFKA_RESP_ERR_GROUP_AUTHORIZATION_FAILED = 30,
    RD_KAFKA_RESP_ERR_CLUSTER_AUTHORIZATION_FAILED = 31,
    RD_KAFKA_RESP_ERR_INVALID_TIMESTAMP = 32,
    RD_KAFKA_RESP_ERR_UNSUPPORTED_SASL_MECHANISM = 33,
    RD_KAFKA_RESP_ERR_ILLEGAL_SASL_STATE = 34,
    RD_KAFKA_RESP_ERR_UNSUPPORTED_VERSION = 35,
    RD_KAFKA_RESP_ERR_END_ALL = 36,
}
#[repr(C)]
#[derive(Copy, Clone)]
#[derive(Debug)]
pub struct rd_kafka_err_desc {
    pub code: rd_kafka_resp_err_t,
    pub name: *const ::libc::c_char,
    pub desc: *const ::libc::c_char,
}
impl ::core::default::Default for rd_kafka_err_desc {
    fn default() -> Self { unsafe { ::core::mem::zeroed() } }
}
#[repr(C)]
#[derive(Copy, Clone)]
#[derive(Debug)]
pub struct rd_kafka_topic_partition_s {
    pub topic: *mut ::libc::c_char,
    pub partition: int32_t,
    pub offset: int64_t,
    pub metadata: *mut ::libc::c_void,
    pub metadata_size: size_t,
    pub opaque: *mut ::libc::c_void,
    pub err: rd_kafka_resp_err_t,
    pub _private: *mut ::libc::c_void,
}
impl ::core::default::Default for rd_kafka_topic_partition_s {
    fn default() -> Self { unsafe { ::core::mem::zeroed() } }
}
pub type rd_kafka_topic_partition_t = rd_kafka_topic_partition_s;
#[repr(C)]
#[derive(Copy, Clone)]
#[derive(Debug)]
pub struct rd_kafka_topic_partition_list_s {
    pub cnt: ::libc::c_int,
    pub size: ::libc::c_int,
    pub elems: *mut rd_kafka_topic_partition_t,
}
impl ::core::default::Default for rd_kafka_topic_partition_list_s {
    fn default() -> Self { unsafe { ::core::mem::zeroed() } }
}
pub type rd_kafka_topic_partition_list_t = rd_kafka_topic_partition_list_s;
#[repr(C)]
#[derive(Copy, Clone)]
#[derive(Debug)]
pub struct rd_kafka_message_s {
    pub err: rd_kafka_resp_err_t,
    pub rkt: *mut rd_kafka_topic_t,
    pub partition: int32_t,
    pub payload: *mut ::libc::c_void,
    pub len: size_t,
    pub key: *mut ::libc::c_void,
    pub key_len: size_t,
    pub offset: int64_t,
    pub _private: *mut ::libc::c_void,
}
impl ::core::default::Default for rd_kafka_message_s {
    fn default() -> Self { unsafe { ::core::mem::zeroed() } }
}
pub type rd_kafka_message_t = rd_kafka_message_s;
#[derive(Copy, Clone)]
#[repr(i32)]
#[derive(Debug)]
pub enum rd_kafka_conf_res_t {
    RD_KAFKA_CONF_UNKNOWN = -2,
    RD_KAFKA_CONF_INVALID = -1,
    RD_KAFKA_CONF_OK = 0,
}
#[repr(C)]
#[derive(Copy, Clone)]
#[derive(Debug)]
pub struct rd_kafka_metadata_broker {
    pub id: int32_t,
    pub host: *mut ::libc::c_char,
    pub port: ::libc::c_int,
    _bindgen_padding_0_: [u8; 4usize],
}
impl ::core::default::Default for rd_kafka_metadata_broker {
    fn default() -> Self { unsafe { ::core::mem::zeroed() } }
}
pub type rd_kafka_metadata_broker_t = rd_kafka_metadata_broker;
#[repr(C)]
#[derive(Copy, Clone)]
#[derive(Debug)]
pub struct rd_kafka_metadata_partition {
    pub id: int32_t,
    pub err: rd_kafka_resp_err_t,
    pub leader: int32_t,
    pub replica_cnt: ::libc::c_int,
    pub replicas: *mut int32_t,
    pub isr_cnt: ::libc::c_int,
    pub isrs: *mut int32_t,
}
impl ::core::default::Default for rd_kafka_metadata_partition {
    fn default() -> Self { unsafe { ::core::mem::zeroed() } }
}
pub type rd_kafka_metadata_partition_t = rd_kafka_metadata_partition;
#[repr(C)]
#[derive(Copy, Clone)]
#[derive(Debug)]
pub struct rd_kafka_metadata_topic {
    pub topic: *mut ::libc::c_char,
    pub partition_cnt: ::libc::c_int,
    pub partitions: *mut rd_kafka_metadata_partition,
    pub err: rd_kafka_resp_err_t,
    _bindgen_padding_0_: [u8; 4usize],
}
impl ::core::default::Default for rd_kafka_metadata_topic {
    fn default() -> Self { unsafe { ::core::mem::zeroed() } }
}
pub type rd_kafka_metadata_topic_t = rd_kafka_metadata_topic;
#[repr(C)]
#[derive(Copy, Clone)]
#[derive(Debug)]
pub struct rd_kafka_metadata {
    pub broker_cnt: ::libc::c_int,
    pub brokers: *mut rd_kafka_metadata_broker,
    pub topic_cnt: ::libc::c_int,
    pub topics: *mut rd_kafka_metadata_topic,
    pub orig_broker_id: int32_t,
    pub orig_broker_name: *mut ::libc::c_char,
}
impl ::core::default::Default for rd_kafka_metadata {
    fn default() -> Self { unsafe { ::core::mem::zeroed() } }
}
pub type rd_kafka_metadata_t = rd_kafka_metadata;
#[repr(C)]
#[derive(Copy, Clone)]
#[derive(Debug)]
pub struct rd_kafka_group_member_info {
    pub member_id: *mut ::libc::c_char,
    pub client_id: *mut ::libc::c_char,
    pub client_host: *mut ::libc::c_char,
    pub member_metadata: *mut ::libc::c_void,
    pub member_metadata_size: ::libc::c_int,
    pub member_assignment: *mut ::libc::c_void,
    pub member_assignment_size: ::libc::c_int,
    _bindgen_padding_0_: [u8; 4usize],
}
impl ::core::default::Default for rd_kafka_group_member_info {
    fn default() -> Self { unsafe { ::core::mem::zeroed() } }
}
#[repr(C)]
#[derive(Copy, Clone)]
#[derive(Debug)]
pub struct rd_kafka_group_info {
    pub broker: rd_kafka_metadata_broker,
    pub group: *mut ::libc::c_char,
    pub err: rd_kafka_resp_err_t,
    pub state: *mut ::libc::c_char,
    pub protocol_type: *mut ::libc::c_char,
    pub protocol: *mut ::libc::c_char,
    pub members: *mut rd_kafka_group_member_info,
    pub member_cnt: ::libc::c_int,
    _bindgen_padding_0_: [u8; 4usize],
}
impl ::core::default::Default for rd_kafka_group_info {
    fn default() -> Self { unsafe { ::core::mem::zeroed() } }
}
#[repr(C)]
#[derive(Copy, Clone)]
#[derive(Debug)]
pub struct rd_kafka_group_list {
    pub groups: *mut rd_kafka_group_info,
    pub group_cnt: ::libc::c_int,
    _bindgen_padding_0_: [u8; 4usize],
}
impl ::core::default::Default for rd_kafka_group_list {
    fn default() -> Self { unsafe { ::core::mem::zeroed() } }
}
extern "C" {
    pub static mut _IO_2_1_stdin_: _IO_FILE_plus;
    pub static mut _IO_2_1_stdout_: _IO_FILE_plus;
    pub static mut _IO_2_1_stderr_: _IO_FILE_plus;
    pub static mut stdin: *mut _IO_FILE;
    pub static mut stdout: *mut _IO_FILE;
    pub static mut stderr: *mut _IO_FILE;
    pub static mut sys_nerr: ::libc::c_int;
    pub static mut sys_errlist: [*const ::libc::c_char; 0usize];
}
extern "C" {
    pub fn __underflow(arg1: *mut _IO_FILE) -> ::libc::c_int;
    pub fn __uflow(arg1: *mut _IO_FILE) -> ::libc::c_int;
    pub fn __overflow(arg1: *mut _IO_FILE, arg2: ::libc::c_int)
     -> ::libc::c_int;
    pub fn _IO_getc(__fp: *mut _IO_FILE) -> ::libc::c_int;
    pub fn _IO_putc(__c: ::libc::c_int, __fp: *mut _IO_FILE) -> ::libc::c_int;
    pub fn _IO_feof(__fp: *mut _IO_FILE) -> ::libc::c_int;
    pub fn _IO_ferror(__fp: *mut _IO_FILE) -> ::libc::c_int;
    pub fn _IO_peekc_locked(__fp: *mut _IO_FILE) -> ::libc::c_int;
    pub fn _IO_flockfile(arg1: *mut _IO_FILE);
    pub fn _IO_funlockfile(arg1: *mut _IO_FILE);
    pub fn _IO_ftrylockfile(arg1: *mut _IO_FILE) -> ::libc::c_int;
    pub fn _IO_vfscanf(arg1: *mut _IO_FILE, arg2: *const ::libc::c_char,
                       arg3: __gnuc_va_list, arg4: *mut ::libc::c_int)
     -> ::libc::c_int;
    pub fn _IO_vfprintf(arg1: *mut _IO_FILE, arg2: *const ::libc::c_char,
                        arg3: __gnuc_va_list) -> ::libc::c_int;
    pub fn _IO_padn(arg1: *mut _IO_FILE, arg2: ::libc::c_int, arg3: __ssize_t)
     -> __ssize_t;
    pub fn _IO_sgetn(arg1: *mut _IO_FILE, arg2: *mut ::libc::c_void,
                     arg3: size_t) -> size_t;
    pub fn _IO_seekoff(arg1: *mut _IO_FILE, arg2: __off64_t,
                       arg3: ::libc::c_int, arg4: ::libc::c_int) -> __off64_t;
    pub fn _IO_seekpos(arg1: *mut _IO_FILE, arg2: __off64_t,
                       arg3: ::libc::c_int) -> __off64_t;
    pub fn _IO_free_backup_area(arg1: *mut _IO_FILE);
    pub fn remove(__filename: *const ::libc::c_char) -> ::libc::c_int;
    pub fn rename(__old: *const ::libc::c_char, __new: *const ::libc::c_char)
     -> ::libc::c_int;
    pub fn renameat(__oldfd: ::libc::c_int, __old: *const ::libc::c_char,
                    __newfd: ::libc::c_int, __new: *const ::libc::c_char)
     -> ::libc::c_int;
    pub fn tmpfile() -> *mut FILE;
    pub fn tmpnam(__s: *mut ::libc::c_char) -> *mut ::libc::c_char;
    pub fn tmpnam_r(__s: *mut ::libc::c_char) -> *mut ::libc::c_char;
    pub fn tempnam(__dir: *const ::libc::c_char, __pfx: *const ::libc::c_char)
     -> *mut ::libc::c_char;
    pub fn fclose(__stream: *mut FILE) -> ::libc::c_int;
    pub fn fflush(__stream: *mut FILE) -> ::libc::c_int;
    pub fn fflush_unlocked(__stream: *mut FILE) -> ::libc::c_int;
    pub fn fopen(__filename: *const ::libc::c_char,
                 __modes: *const ::libc::c_char) -> *mut FILE;
    pub fn freopen(__filename: *const ::libc::c_char,
                   __modes: *const ::libc::c_char, __stream: *mut FILE)
     -> *mut FILE;
    pub fn fdopen(__fd: ::libc::c_int, __modes: *const ::libc::c_char)
     -> *mut FILE;
    pub fn fmemopen(__s: *mut ::libc::c_void, __len: size_t,
                    __modes: *const ::libc::c_char) -> *mut FILE;
    pub fn open_memstream(__bufloc: *mut *mut ::libc::c_char,
                          __sizeloc: *mut size_t) -> *mut FILE;
    pub fn setbuf(__stream: *mut FILE, __buf: *mut ::libc::c_char);
    pub fn setvbuf(__stream: *mut FILE, __buf: *mut ::libc::c_char,
                   __modes: ::libc::c_int, __n: size_t) -> ::libc::c_int;
    pub fn setbuffer(__stream: *mut FILE, __buf: *mut ::libc::c_char,
                     __size: size_t);
    pub fn setlinebuf(__stream: *mut FILE);
    pub fn fprintf(__stream: *mut FILE, __format: *const ::libc::c_char, ...)
     -> ::libc::c_int;
    pub fn printf(__format: *const ::libc::c_char, ...) -> ::libc::c_int;
    pub fn sprintf(__s: *mut ::libc::c_char,
                   __format: *const ::libc::c_char, ...) -> ::libc::c_int;
    pub fn vfprintf(__s: *mut FILE, __format: *const ::libc::c_char,
                    __arg: __gnuc_va_list) -> ::libc::c_int;
    pub fn vprintf(__format: *const ::libc::c_char, __arg: __gnuc_va_list)
     -> ::libc::c_int;
    pub fn vsprintf(__s: *mut ::libc::c_char, __format: *const ::libc::c_char,
                    __arg: __gnuc_va_list) -> ::libc::c_int;
    pub fn snprintf(__s: *mut ::libc::c_char, __maxlen: size_t,
                    __format: *const ::libc::c_char, ...) -> ::libc::c_int;
    pub fn vsnprintf(__s: *mut ::libc::c_char, __maxlen: size_t,
                     __format: *const ::libc::c_char, __arg: __gnuc_va_list)
     -> ::libc::c_int;
    pub fn vdprintf(__fd: ::libc::c_int, __fmt: *const ::libc::c_char,
                    __arg: __gnuc_va_list) -> ::libc::c_int;
    pub fn dprintf(__fd: ::libc::c_int, __fmt: *const ::libc::c_char, ...)
     -> ::libc::c_int;
    pub fn fscanf(__stream: *mut FILE, __format: *const ::libc::c_char, ...)
     -> ::libc::c_int;
    pub fn scanf(__format: *const ::libc::c_char, ...) -> ::libc::c_int;
    pub fn sscanf(__s: *const ::libc::c_char,
                  __format: *const ::libc::c_char, ...) -> ::libc::c_int;
    pub fn vfscanf(__s: *mut FILE, __format: *const ::libc::c_char,
                   __arg: __gnuc_va_list) -> ::libc::c_int;
    pub fn vscanf(__format: *const ::libc::c_char, __arg: __gnuc_va_list)
     -> ::libc::c_int;
    pub fn vsscanf(__s: *const ::libc::c_char,
                   __format: *const ::libc::c_char, __arg: __gnuc_va_list)
     -> ::libc::c_int;
    pub fn fgetc(__stream: *mut FILE) -> ::libc::c_int;
    pub fn getc(__stream: *mut FILE) -> ::libc::c_int;
    pub fn getchar() -> ::libc::c_int;
    pub fn getc_unlocked(__stream: *mut FILE) -> ::libc::c_int;
    pub fn getchar_unlocked() -> ::libc::c_int;
    pub fn fgetc_unlocked(__stream: *mut FILE) -> ::libc::c_int;
    pub fn fputc(__c: ::libc::c_int, __stream: *mut FILE) -> ::libc::c_int;
    pub fn putc(__c: ::libc::c_int, __stream: *mut FILE) -> ::libc::c_int;
    pub fn putchar(__c: ::libc::c_int) -> ::libc::c_int;
    pub fn fputc_unlocked(__c: ::libc::c_int, __stream: *mut FILE)
     -> ::libc::c_int;
    pub fn putc_unlocked(__c: ::libc::c_int, __stream: *mut FILE)
     -> ::libc::c_int;
    pub fn putchar_unlocked(__c: ::libc::c_int) -> ::libc::c_int;
    pub fn getw(__stream: *mut FILE) -> ::libc::c_int;
    pub fn putw(__w: ::libc::c_int, __stream: *mut FILE) -> ::libc::c_int;
    pub fn fgets(__s: *mut ::libc::c_char, __n: ::libc::c_int,
                 __stream: *mut FILE) -> *mut ::libc::c_char;
    pub fn __getdelim(__lineptr: *mut *mut ::libc::c_char, __n: *mut size_t,
                      __delimiter: ::libc::c_int, __stream: *mut FILE)
     -> __ssize_t;
    pub fn getdelim(__lineptr: *mut *mut ::libc::c_char, __n: *mut size_t,
                    __delimiter: ::libc::c_int, __stream: *mut FILE)
     -> __ssize_t;
    pub fn getline(__lineptr: *mut *mut ::libc::c_char, __n: *mut size_t,
                   __stream: *mut FILE) -> __ssize_t;
    pub fn fputs(__s: *const ::libc::c_char, __stream: *mut FILE)
     -> ::libc::c_int;
    pub fn puts(__s: *const ::libc::c_char) -> ::libc::c_int;
    pub fn ungetc(__c: ::libc::c_int, __stream: *mut FILE) -> ::libc::c_int;
    pub fn fread(__ptr: *mut ::libc::c_void, __size: size_t, __n: size_t,
                 __stream: *mut FILE) -> size_t;
    pub fn fwrite(__ptr: *const ::libc::c_void, __size: size_t, __n: size_t,
                  __s: *mut FILE) -> size_t;
    pub fn fread_unlocked(__ptr: *mut ::libc::c_void, __size: size_t,
                          __n: size_t, __stream: *mut FILE) -> size_t;
    pub fn fwrite_unlocked(__ptr: *const ::libc::c_void, __size: size_t,
                           __n: size_t, __stream: *mut FILE) -> size_t;
    pub fn fseek(__stream: *mut FILE, __off: ::libc::c_long,
                 __whence: ::libc::c_int) -> ::libc::c_int;
    pub fn ftell(__stream: *mut FILE) -> ::libc::c_long;
    pub fn rewind(__stream: *mut FILE);
    pub fn fseeko(__stream: *mut FILE, __off: __off_t,
                  __whence: ::libc::c_int) -> ::libc::c_int;
    pub fn ftello(__stream: *mut FILE) -> __off_t;
    pub fn fgetpos(__stream: *mut FILE, __pos: *mut fpos_t) -> ::libc::c_int;
    pub fn fsetpos(__stream: *mut FILE, __pos: *const fpos_t)
     -> ::libc::c_int;
    pub fn clearerr(__stream: *mut FILE);
    pub fn feof(__stream: *mut FILE) -> ::libc::c_int;
    pub fn ferror(__stream: *mut FILE) -> ::libc::c_int;
    pub fn clearerr_unlocked(__stream: *mut FILE);
    pub fn feof_unlocked(__stream: *mut FILE) -> ::libc::c_int;
    pub fn ferror_unlocked(__stream: *mut FILE) -> ::libc::c_int;
    pub fn perror(__s: *const ::libc::c_char);
    pub fn fileno(__stream: *mut FILE) -> ::libc::c_int;
    pub fn fileno_unlocked(__stream: *mut FILE) -> ::libc::c_int;
    pub fn popen(__command: *const ::libc::c_char,
                 __modes: *const ::libc::c_char) -> *mut FILE;
    pub fn pclose(__stream: *mut FILE) -> ::libc::c_int;
    pub fn ctermid(__s: *mut ::libc::c_char) -> *mut ::libc::c_char;
    pub fn flockfile(__stream: *mut FILE);
    pub fn ftrylockfile(__stream: *mut FILE) -> ::libc::c_int;
    pub fn funlockfile(__stream: *mut FILE);
    pub fn imaxabs(__n: intmax_t) -> intmax_t;
    pub fn imaxdiv(__numer: intmax_t, __denom: intmax_t) -> imaxdiv_t;
    pub fn strtoimax(__nptr: *const ::libc::c_char,
                     __endptr: *mut *mut ::libc::c_char,
                     __base: ::libc::c_int) -> intmax_t;
    pub fn strtoumax(__nptr: *const ::libc::c_char,
                     __endptr: *mut *mut ::libc::c_char,
                     __base: ::libc::c_int) -> uintmax_t;
    pub fn wcstoimax(__nptr: *const __gwchar_t,
                     __endptr: *mut *mut __gwchar_t, __base: ::libc::c_int)
     -> intmax_t;
    pub fn wcstoumax(__nptr: *const __gwchar_t,
                     __endptr: *mut *mut __gwchar_t, __base: ::libc::c_int)
     -> uintmax_t;
    pub fn select(__nfds: ::libc::c_int, __readfds: *mut fd_set,
                  __writefds: *mut fd_set, __exceptfds: *mut fd_set,
                  __timeout: *mut timeval) -> ::libc::c_int;
    pub fn pselect(__nfds: ::libc::c_int, __readfds: *mut fd_set,
                   __writefds: *mut fd_set, __exceptfds: *mut fd_set,
                   __timeout: *const timespec, __sigmask: *const __sigset_t)
     -> ::libc::c_int;
    pub fn gnu_dev_major(__dev: ::libc::c_ulonglong) -> ::libc::c_uint;
    pub fn gnu_dev_minor(__dev: ::libc::c_ulonglong) -> ::libc::c_uint;
    pub fn gnu_dev_makedev(__major: ::libc::c_uint, __minor: ::libc::c_uint)
     -> ::libc::c_ulonglong;
    pub fn rd_kafka_version() -> ::libc::c_int;
    pub fn rd_kafka_version_str() -> *const ::libc::c_char;
    pub fn rd_kafka_get_debug_contexts() -> *const ::libc::c_char;
    pub fn rd_kafka_get_err_descs(errdescs: *mut *const rd_kafka_err_desc,
                                  cntp: *mut size_t);
    pub fn rd_kafka_err2str(err: rd_kafka_resp_err_t)
     -> *const ::libc::c_char;
    pub fn rd_kafka_err2name(err: rd_kafka_resp_err_t)
     -> *const ::libc::c_char;
    pub fn rd_kafka_last_error() -> rd_kafka_resp_err_t;
    pub fn rd_kafka_errno2err(errnox: ::libc::c_int) -> rd_kafka_resp_err_t;
    pub fn rd_kafka_errno() -> ::libc::c_int;
    pub fn rd_kafka_topic_partition_list_new(size: ::libc::c_int)
     -> *mut rd_kafka_topic_partition_list_t;
    pub fn rd_kafka_topic_partition_list_destroy(rkparlist:
                                                     *mut rd_kafka_topic_partition_list_t);
    pub fn rd_kafka_topic_partition_list_add(rktparlist:
                                                 *mut rd_kafka_topic_partition_list_t,
                                             topic: *const ::libc::c_char,
                                             partition: int32_t)
     -> *mut rd_kafka_topic_partition_t;
    pub fn rd_kafka_topic_partition_list_add_range(rktparlist:
                                                       *mut rd_kafka_topic_partition_list_t,
                                                   topic:
                                                       *const ::libc::c_char,
                                                   start: int32_t,
                                                   stop: int32_t);
    pub fn rd_kafka_topic_partition_list_del(rktparlist:
                                                 *mut rd_kafka_topic_partition_list_t,
                                             topic: *const ::libc::c_char,
                                             partition: int32_t)
     -> ::libc::c_int;
    pub fn rd_kafka_topic_partition_list_del_by_idx(rktparlist:
                                                        *mut rd_kafka_topic_partition_list_t,
                                                    idx: ::libc::c_int)
     -> ::libc::c_int;
    pub fn rd_kafka_topic_partition_list_copy(src:
                                                  *const rd_kafka_topic_partition_list_t)
     -> *mut rd_kafka_topic_partition_list_t;
    pub fn rd_kafka_topic_partition_list_set_offset(rktparlist:
                                                        *mut rd_kafka_topic_partition_list_t,
                                                    topic:
                                                        *const ::libc::c_char,
                                                    partition: int32_t,
                                                    offset: int64_t)
     -> rd_kafka_resp_err_t;
    pub fn rd_kafka_topic_partition_list_find(rktparlist:
                                                  *mut rd_kafka_topic_partition_list_t,
                                              topic: *const ::libc::c_char,
                                              partition: int32_t)
     -> *mut rd_kafka_topic_partition_t;
    pub fn rd_kafka_message_destroy(rkmessage: *mut rd_kafka_message_t);
    pub fn rd_kafka_message_timestamp(rkmessage: *const rd_kafka_message_t,
                                      tstype: *mut rd_kafka_timestamp_type_t)
     -> int64_t;
    pub fn rd_kafka_conf_new() -> *mut rd_kafka_conf_t;
    pub fn rd_kafka_conf_destroy(conf: *mut rd_kafka_conf_t);
    pub fn rd_kafka_conf_dup(conf: *const rd_kafka_conf_t)
     -> *mut rd_kafka_conf_t;
    pub fn rd_kafka_conf_set(conf: *mut rd_kafka_conf_t,
                             name: *const ::libc::c_char,
                             value: *const ::libc::c_char,
                             errstr: *mut ::libc::c_char, errstr_size: size_t)
     -> rd_kafka_conf_res_t;
    pub fn rd_kafka_conf_set_dr_cb(conf: *mut rd_kafka_conf_t,
                                   dr_cb:
                                       ::core::option::Option<unsafe extern "C" fn(rk:
                                                                                       *mut rd_kafka_t,
                                                                                   payload:
                                                                                       *mut ::libc::c_void,
                                                                                   len:
                                                                                       size_t,
                                                                                   err:
                                                                                       rd_kafka_resp_err_t,
                                                                                   opaque:
                                                                                       *mut ::libc::c_void,
                                                                                   msg_opaque:
                                                                                       *mut ::libc::c_void)>);
    pub fn rd_kafka_conf_set_dr_msg_cb(conf: *mut rd_kafka_conf_t,
                                       dr_msg_cb:
                                           ::core::option::Option<unsafe extern "C" fn(rk:
                                                                                           *mut rd_kafka_t,
                                                                                       rkmessage:
                                                                                           *const rd_kafka_message_t,
                                                                                       opaque:
                                                                                           *mut ::libc::c_void)>);
    pub fn rd_kafka_conf_set_consume_cb(conf: *mut rd_kafka_conf_t,
                                        consume_cb:
                                            ::core::option::Option<unsafe extern "C" fn(rkmessage:
                                                                                            *mut rd_kafka_message_t,
                                                                                        opaque:
                                                                                            *mut ::libc::c_void)>);
    pub fn rd_kafka_conf_set_rebalance_cb(conf: *mut rd_kafka_conf_t,
                                          rebalance_cb:
                                              ::core::option::Option<unsafe extern "C" fn(rk:
                                                                                              *mut rd_kafka_t,
                                                                                          err:
                                                                                              rd_kafka_resp_err_t,
                                                                                          partitions:
                                                                                              *mut rd_kafka_topic_partition_list_t,
                                                                                          opaque:
                                                                                              *mut ::libc::c_void)>);
    pub fn rd_kafka_conf_set_offset_commit_cb(conf: *mut rd_kafka_conf_t,
                                              offset_commit_cb:
                                                  ::core::option::Option<unsafe extern "C" fn(rk:
                                                                                                  *mut rd_kafka_t,
                                                                                              err:
                                                                                                  rd_kafka_resp_err_t,
                                                                                              offsets:
                                                                                                  *mut rd_kafka_topic_partition_list_t,
                                                                                              opaque:
                                                                                                  *mut ::libc::c_void)>);
    pub fn rd_kafka_conf_set_error_cb(conf: *mut rd_kafka_conf_t,
                                      error_cb:
                                          ::core::option::Option<unsafe extern "C" fn(rk:
                                                                                          *mut rd_kafka_t,
                                                                                      err:
                                                                                          ::libc::c_int,
                                                                                      reason:
                                                                                          *const ::libc::c_char,
                                                                                      opaque:
                                                                                          *mut ::libc::c_void)>);
    pub fn rd_kafka_conf_set_throttle_cb(conf: *mut rd_kafka_conf_t,
                                         throttle_cb:
                                             ::core::option::Option<unsafe extern "C" fn(rk:
                                                                                             *mut rd_kafka_t,
                                                                                         broker_name:
                                                                                             *const ::libc::c_char,
                                                                                         broker_id:
                                                                                             int32_t,
                                                                                         throttle_time_ms:
                                                                                             ::libc::c_int,
                                                                                         opaque:
                                                                                             *mut ::libc::c_void)>);
    pub fn rd_kafka_conf_set_log_cb(conf: *mut rd_kafka_conf_t,
                                    log_cb:
                                        ::core::option::Option<unsafe extern "C" fn(rk:
                                                                                        *const rd_kafka_t,
                                                                                    level:
                                                                                        ::libc::c_int,
                                                                                    fac:
                                                                                        *const ::libc::c_char,
                                                                                    buf:
                                                                                        *const ::libc::c_char)>);
    pub fn rd_kafka_conf_set_stats_cb(conf: *mut rd_kafka_conf_t,
                                      stats_cb:
                                          ::core::option::Option<unsafe extern "C" fn(rk:
                                                                                          *mut rd_kafka_t,
                                                                                      json:
                                                                                          *mut ::libc::c_char,
                                                                                      json_len:
                                                                                          size_t,
                                                                                      opaque:
                                                                                          *mut ::libc::c_void)
                                                                     ->
                                                                         ::libc::c_int>);
    pub fn rd_kafka_conf_set_socket_cb(conf: *mut rd_kafka_conf_t,
                                       socket_cb:
                                           ::core::option::Option<unsafe extern "C" fn(domain:
                                                                                           ::libc::c_int,
                                                                                       type_:
                                                                                           ::libc::c_int,
                                                                                       protocol:
                                                                                           ::libc::c_int,
                                                                                       opaque:
                                                                                           *mut ::libc::c_void)
                                                                      ->
                                                                          ::libc::c_int>);
    pub fn rd_kafka_conf_set_open_cb(conf: *mut rd_kafka_conf_t,
                                     open_cb:
                                         ::core::option::Option<unsafe extern "C" fn(pathname:
                                                                                         *const ::libc::c_char,
                                                                                     flags:
                                                                                         ::libc::c_int,
                                                                                     mode:
                                                                                         mode_t,
                                                                                     opaque:
                                                                                         *mut ::libc::c_void)
                                                                    ->
                                                                        ::libc::c_int>);
    pub fn rd_kafka_conf_set_opaque(conf: *mut rd_kafka_conf_t,
                                    opaque: *mut ::libc::c_void);
    pub fn rd_kafka_opaque(rk: *const rd_kafka_t) -> *mut ::libc::c_void;
    pub fn rd_kafka_conf_set_default_topic_conf(conf: *mut rd_kafka_conf_t,
                                                tconf:
                                                    *mut rd_kafka_topic_conf_t);
    pub fn rd_kafka_conf_get(conf: *const rd_kafka_conf_t,
                             name: *const ::libc::c_char,
                             dest: *mut ::libc::c_char,
                             dest_size: *mut size_t) -> rd_kafka_conf_res_t;
    pub fn rd_kafka_topic_conf_get(conf: *const rd_kafka_topic_conf_t,
                                   name: *const ::libc::c_char,
                                   dest: *mut ::libc::c_char,
                                   dest_size: *mut size_t)
     -> rd_kafka_conf_res_t;
    pub fn rd_kafka_conf_dump(conf: *mut rd_kafka_conf_t, cntp: *mut size_t)
     -> *mut *const ::libc::c_char;
    pub fn rd_kafka_topic_conf_dump(conf: *mut rd_kafka_topic_conf_t,
                                    cntp: *mut size_t)
     -> *mut *const ::libc::c_char;
    pub fn rd_kafka_conf_dump_free(arr: *mut *const ::libc::c_char,
                                   cnt: size_t);
    pub fn rd_kafka_conf_properties_show(fp: *mut FILE);
    pub fn rd_kafka_topic_conf_new() -> *mut rd_kafka_topic_conf_t;
    pub fn rd_kafka_topic_conf_dup(conf: *const rd_kafka_topic_conf_t)
     -> *mut rd_kafka_topic_conf_t;
    pub fn rd_kafka_topic_conf_destroy(topic_conf:
                                           *mut rd_kafka_topic_conf_t);
    pub fn rd_kafka_topic_conf_set(conf: *mut rd_kafka_topic_conf_t,
                                   name: *const ::libc::c_char,
                                   value: *const ::libc::c_char,
                                   errstr: *mut ::libc::c_char,
                                   errstr_size: size_t)
     -> rd_kafka_conf_res_t;
    pub fn rd_kafka_topic_conf_set_opaque(conf: *mut rd_kafka_topic_conf_t,
                                          opaque: *mut ::libc::c_void);
    pub fn rd_kafka_topic_conf_set_partitioner_cb(topic_conf:
                                                      *mut rd_kafka_topic_conf_t,
                                                  partitioner:
                                                      ::core::option::Option<unsafe extern "C" fn(rkt:
                                                                                                      *const rd_kafka_topic_t,
                                                                                                  keydata:
                                                                                                      *const ::libc::c_void,
                                                                                                  keylen:
                                                                                                      size_t,
                                                                                                  partition_cnt:
                                                                                                      int32_t,
                                                                                                  rkt_opaque:
                                                                                                      *mut ::libc::c_void,
                                                                                                  msg_opaque:
                                                                                                      *mut ::libc::c_void)
                                                                                 ->
                                                                                     int32_t>);
    pub fn rd_kafka_topic_partition_available(rkt: *const rd_kafka_topic_t,
                                              partition: int32_t)
     -> ::libc::c_int;
    pub fn rd_kafka_msg_partitioner_random(rkt: *const rd_kafka_topic_t,
                                           key: *const ::libc::c_void,
                                           keylen: size_t,
                                           partition_cnt: int32_t,
                                           opaque: *mut ::libc::c_void,
                                           msg_opaque: *mut ::libc::c_void)
     -> int32_t;
    pub fn rd_kafka_msg_partitioner_consistent(rkt: *const rd_kafka_topic_t,
                                               key: *const ::libc::c_void,
                                               keylen: size_t,
                                               partition_cnt: int32_t,
                                               opaque: *mut ::libc::c_void,
                                               msg_opaque:
                                                   *mut ::libc::c_void)
     -> int32_t;
    pub fn rd_kafka_msg_partitioner_consistent_random(rkt:
                                                          *const rd_kafka_topic_t,
                                                      key:
                                                          *const ::libc::c_void,
                                                      keylen: size_t,
                                                      partition_cnt: int32_t,
                                                      opaque:
                                                          *mut ::libc::c_void,
                                                      msg_opaque:
                                                          *mut ::libc::c_void)
     -> int32_t;
    pub fn rd_kafka_new(type_: rd_kafka_type_t, conf: *mut rd_kafka_conf_t,
                        errstr: *mut ::libc::c_char, errstr_size: size_t)
     -> *mut rd_kafka_t;
    pub fn rd_kafka_destroy(rk: *mut rd_kafka_t);
    pub fn rd_kafka_name(rk: *const rd_kafka_t) -> *const ::libc::c_char;
    pub fn rd_kafka_memberid(rk: *const rd_kafka_t) -> *mut ::libc::c_char;
    pub fn rd_kafka_topic_new(rk: *mut rd_kafka_t,
                              topic: *const ::libc::c_char,
                              conf: *mut rd_kafka_topic_conf_t)
     -> *mut rd_kafka_topic_t;
    pub fn rd_kafka_topic_destroy(rkt: *mut rd_kafka_topic_t);
    pub fn rd_kafka_topic_name(rkt: *const rd_kafka_topic_t)
     -> *const ::libc::c_char;
    pub fn rd_kafka_topic_opaque(rkt: *const rd_kafka_topic_t)
     -> *mut ::libc::c_void;
    pub fn rd_kafka_poll(rk: *mut rd_kafka_t, timeout_ms: ::libc::c_int)
     -> ::libc::c_int;
    pub fn rd_kafka_yield(rk: *mut rd_kafka_t);
    pub fn rd_kafka_pause_partitions(rk: *mut rd_kafka_t,
                                     partitions:
                                         *mut rd_kafka_topic_partition_list_t)
     -> rd_kafka_resp_err_t;
    pub fn rd_kafka_resume_partitions(rk: *mut rd_kafka_t,
                                      partitions:
                                          *mut rd_kafka_topic_partition_list_t)
     -> rd_kafka_resp_err_t;
    pub fn rd_kafka_query_watermark_offsets(rk: *mut rd_kafka_t,
                                            topic: *const ::libc::c_char,
                                            partition: int32_t,
                                            low: *mut int64_t,
                                            high: *mut int64_t,
                                            timeout_ms: ::libc::c_int)
     -> rd_kafka_resp_err_t;
    pub fn rd_kafka_get_watermark_offsets(rk: *mut rd_kafka_t,
                                          topic: *const ::libc::c_char,
                                          partition: int32_t,
                                          low: *mut int64_t,
                                          high: *mut int64_t)
     -> rd_kafka_resp_err_t;
    pub fn rd_kafka_mem_free(rk: *mut rd_kafka_t, ptr: *mut ::libc::c_void);
    pub fn rd_kafka_queue_new(rk: *mut rd_kafka_t) -> *mut rd_kafka_queue_t;
    pub fn rd_kafka_queue_destroy(rkqu: *mut rd_kafka_queue_t);
    pub fn rd_kafka_consume_start(rkt: *mut rd_kafka_topic_t,
                                  partition: int32_t, offset: int64_t)
     -> ::libc::c_int;
    pub fn rd_kafka_consume_start_queue(rkt: *mut rd_kafka_topic_t,
                                        partition: int32_t, offset: int64_t,
                                        rkqu: *mut rd_kafka_queue_t)
     -> ::libc::c_int;
    pub fn rd_kafka_consume_stop(rkt: *mut rd_kafka_topic_t,
                                 partition: int32_t) -> ::libc::c_int;
    pub fn rd_kafka_seek(rkt: *mut rd_kafka_topic_t, partition: int32_t,
                         offset: int64_t, timeout_ms: ::libc::c_int)
     -> rd_kafka_resp_err_t;
    pub fn rd_kafka_consume(rkt: *mut rd_kafka_topic_t, partition: int32_t,
                            timeout_ms: ::libc::c_int)
     -> *mut rd_kafka_message_t;
    pub fn rd_kafka_consume_batch(rkt: *mut rd_kafka_topic_t,
                                  partition: int32_t,
                                  timeout_ms: ::libc::c_int,
                                  rkmessages: *mut *mut rd_kafka_message_t,
                                  rkmessages_size: size_t) -> ssize_t;
    pub fn rd_kafka_consume_callback(rkt: *mut rd_kafka_topic_t,
                                     partition: int32_t,
                                     timeout_ms: ::libc::c_int,
                                     consume_cb:
                                         ::core::option::Option<unsafe extern "C" fn(rkmessage:
                                                                                         *mut rd_kafka_message_t,
                                                                                     opaque:
                                                                                         *mut ::libc::c_void)>,
                                     opaque: *mut ::libc::c_void)
     -> ::libc::c_int;
    pub fn rd_kafka_consume_queue(rkqu: *mut rd_kafka_queue_t,
                                  timeout_ms: ::libc::c_int)
     -> *mut rd_kafka_message_t;
    pub fn rd_kafka_consume_batch_queue(rkqu: *mut rd_kafka_queue_t,
                                        timeout_ms: ::libc::c_int,
                                        rkmessages:
                                            *mut *mut rd_kafka_message_t,
                                        rkmessages_size: size_t) -> ssize_t;
    pub fn rd_kafka_consume_callback_queue(rkqu: *mut rd_kafka_queue_t,
                                           timeout_ms: ::libc::c_int,
                                           consume_cb:
                                               ::core::option::Option<unsafe extern "C" fn(rkmessage:
                                                                                               *mut rd_kafka_message_t,
                                                                                           opaque:
                                                                                               *mut ::libc::c_void)>,
                                           opaque: *mut ::libc::c_void)
     -> ::libc::c_int;
    pub fn rd_kafka_offset_store(rkt: *mut rd_kafka_topic_t,
                                 partition: int32_t, offset: int64_t)
     -> rd_kafka_resp_err_t;
    pub fn rd_kafka_subscribe(rk: *mut rd_kafka_t,
                              topics: *const rd_kafka_topic_partition_list_t)
     -> rd_kafka_resp_err_t;
    pub fn rd_kafka_unsubscribe(rk: *mut rd_kafka_t) -> rd_kafka_resp_err_t;
    pub fn rd_kafka_subscription(rk: *mut rd_kafka_t,
                                 topics:
                                     *mut *mut rd_kafka_topic_partition_list_t)
     -> rd_kafka_resp_err_t;
    pub fn rd_kafka_consumer_poll(rk: *mut rd_kafka_t,
                                  timeout_ms: ::libc::c_int)
     -> *mut rd_kafka_message_t;
    pub fn rd_kafka_consumer_close(rk: *mut rd_kafka_t)
     -> rd_kafka_resp_err_t;
    pub fn rd_kafka_assign(rk: *mut rd_kafka_t,
                           partitions: *const rd_kafka_topic_partition_list_t)
     -> rd_kafka_resp_err_t;
    pub fn rd_kafka_assignment(rk: *mut rd_kafka_t,
                               partitions:
                                   *mut *mut rd_kafka_topic_partition_list_t)
     -> rd_kafka_resp_err_t;
    pub fn rd_kafka_commit(rk: *mut rd_kafka_t,
                           offsets: *const rd_kafka_topic_partition_list_t,
                           async: ::libc::c_int) -> rd_kafka_resp_err_t;
    pub fn rd_kafka_commit_message(rk: *mut rd_kafka_t,
                                   rkmessage: *const rd_kafka_message_t,
                                   async: ::libc::c_int)
     -> rd_kafka_resp_err_t;
    pub fn rd_kafka_committed(rk: *mut rd_kafka_t,
                              partitions:
                                  *mut rd_kafka_topic_partition_list_t,
                              timeout_ms: ::libc::c_int)
     -> rd_kafka_resp_err_t;
    pub fn rd_kafka_position(rk: *mut rd_kafka_t,
                             partitions: *mut rd_kafka_topic_partition_list_t)
     -> rd_kafka_resp_err_t;
    pub fn rd_kafka_produce(rkt: *mut rd_kafka_topic_t, partition: int32_t,
                            msgflags: ::libc::c_int,
                            payload: *mut ::libc::c_void, len: size_t,
                            key: *const ::libc::c_void, keylen: size_t,
                            msg_opaque: *mut ::libc::c_void) -> ::libc::c_int;
    pub fn rd_kafka_produce_batch(rkt: *mut rd_kafka_topic_t,
                                  partition: int32_t, msgflags: ::libc::c_int,
                                  rkmessages: *mut rd_kafka_message_t,
                                  message_cnt: ::libc::c_int)
     -> ::libc::c_int;
    pub fn rd_kafka_metadata(rk: *mut rd_kafka_t, all_topics: ::libc::c_int,
                             only_rkt: *mut rd_kafka_topic_t,
                             metadatap: *mut *const rd_kafka_metadata,
                             timeout_ms: ::libc::c_int)
     -> rd_kafka_resp_err_t;
    pub fn rd_kafka_metadata_destroy(metadata: *const rd_kafka_metadata);
    pub fn rd_kafka_list_groups(rk: *mut rd_kafka_t,
                                group: *const ::libc::c_char,
                                grplistp: *mut *const rd_kafka_group_list,
                                timeout_ms: ::libc::c_int)
     -> rd_kafka_resp_err_t;
    pub fn rd_kafka_group_list_destroy(grplist: *const rd_kafka_group_list);
    pub fn rd_kafka_brokers_add(rk: *mut rd_kafka_t,
                                brokerlist: *const ::libc::c_char)
     -> ::libc::c_int;
    pub fn rd_kafka_set_logger(rk: *mut rd_kafka_t,
                               func:
                                   ::core::option::Option<unsafe extern "C" fn(rk:
                                                                                   *const rd_kafka_t,
                                                                               level:
                                                                                   ::libc::c_int,
                                                                               fac:
                                                                                   *const ::libc::c_char,
                                                                               buf:
                                                                                   *const ::libc::c_char)>);
    pub fn rd_kafka_set_log_level(rk: *mut rd_kafka_t, level: ::libc::c_int);
    pub fn rd_kafka_log_print(rk: *const rd_kafka_t, level: ::libc::c_int,
                              fac: *const ::libc::c_char,
                              buf: *const ::libc::c_char);
    pub fn rd_kafka_log_syslog(rk: *const rd_kafka_t, level: ::libc::c_int,
                               fac: *const ::libc::c_char,
                               buf: *const ::libc::c_char);
    pub fn rd_kafka_outq_len(rk: *mut rd_kafka_t) -> ::libc::c_int;
    pub fn rd_kafka_dump(fp: *mut FILE, rk: *mut rd_kafka_t);
    pub fn rd_kafka_thread_cnt() -> ::libc::c_int;
    pub fn rd_kafka_wait_destroyed(timeout_ms: ::libc::c_int)
     -> ::libc::c_int;
    pub fn rd_kafka_poll_set_consumer(rk: *mut rd_kafka_t)
     -> rd_kafka_resp_err_t;
}
